### ISSUE TITLE
pytest_mock MockFixture does not accept mock_open

### ISSUE THREAD

**Issue by staticdev** [srittau/python-stubs#1]
If I call `patch` with just the target the stub works, but if I put the arg mock_open I get mypy errors:

```python
from unittest.mock import Mock
import pytest
from pytest_mock import MockFixture

@pytest.fixture
def mock_tomlkit_parse(mocker: MockFixture) -> Mock:
    return mocker.patch("tomlkit.parse") # this works!

@pytest.fixture
def mock_open_valid_file(mocker: MockFixture) -> Mock:
    return mocker.patch("builtins.open", mocker.mock_open(read_data="[x]\na = 3"))
```

Mypy errors:

```sh
tests/test_validation.py: note: In function "mock_open_invalid_file":
tests/test_validation.py:34:5: error: Returning Any from function declared to return "Mock"  [no-any-return]
        return mocker.patch(
        ^
tests/test_validation.py:35:26: error: "MockFixture" has no attribute "mock_open"  [attr-defined]
            "builtins.open", mocker.mock_open(read_data="[x]\na = 3\n[x]\na = 3")
                             ^
```

You can see full example in this PR: https://github.com/staticdev/toml-validator/pull/110

**Comment by srittau** [comment]
These stubs are very incomplete. There are more complete stubs now in typeshed HEAD (and will be in the next mypy release). Unfortunately there is a problem with `mock_open` (and other mocks from `unittest.mock`): Due to google/pytype#612 this is not a proper alias. I will fix it in this branch in the meantime.

**Comment by staticdev** [comment]
This one right? https://github.com/python/typeshed/blob/master/third_party/3/pytest_mock/plugin.pyi

With this stub I don't have the mock_open error, but I still have the first one: `Returning Any from function declared to return "Mock"  [no-any-return]`

**Comment by srittau** [comment]
@staticdev Yeah, as said above, it's still problematic. But please try the updated version in this repository. It won't work with pytype, due to the bug mentioned above, but it should work with mypy.

**Comment by staticdev** [comment]
@srittau I tested with your latest commit, now the error changed:

```
tests/test_validation.py: note: In function "mock_open_invalid_file":
tests/test_validation.py:34:5: error: Returning Any from function declared to return "Mock"  [no-any-return]
        return mocker.patch(
        ^
tests/test_validation.py:35:26: error: Attribute function "mock_open" with type "Callable[[Optional[Any], Any], Any]" does not accept self argument  [misc]
            "builtins.open", mocker.mock_open(read_data="[x]\na = 3\n[x]\na = 3")
                             ^
```

Maybe this one is related to https://github.com/python/mypy/issues/6910
