### ISSUE TITLE
Add information on where to find the removed types

### ISSUE THREAD

**Issue by sfc-gh-dschumann** [srittau/python-stubs#3]
I have come to this repo linked from here: https://github.com/python/typeshed/issues/4263

I expect many people find it that way. And the probablitly that the typing has been implemented and removed is high. It would be great to either:

a) leave a pointer in the file / folder on how to use the types. In this case "mock". Do they provide stubs in a separate package? Or some other method?
b) Have that info in the commit message removing them. Still requires searching all commits. But thats doable.

Thanks for your work!

**Comment by srittau** [comment]
All removed stubs have either been integrated into typeshed and should be installable from PyPI or the packages are now typed upstream. The latter is true for pytest_mock, so for current pytest_mock versions, type stubs should be unnecessary.
